cmd_export: Used absolute path to spec file to avoid wrong determination of spec path. Fixes #185
When spec file is passed as a parameter --spec and path is relative it
caused an error in path determination and gbs export was failing with
error: RPM error while parsing spec: can't parse specfile. This change
fixes the issue.

Change-Id: I1e388e88453423f6c529b0012d60d5251a64838c